version: '3'

volumes:
    redirectionio-agent-data: {}

services:
    nginx:
        build: services/nginx
        env_file: "../.env"
        ports:
            - "8080:80"
        volumes:
            - ../app:/var/www
    redirectionio-agent:
        build: services/redirectionio-agent
        env_file: "../.env"
        environment:
            - INSTANCE_NAME=docker-nginx-custom
        volumes:
            - redirectionio-agent-data:/var/lib/redirectionio
